apiVersion: v1
kind: Service
metadata:
  name: messaging-app-blue-green-service
  labels:
    app: messaging-app
    strategy: blue-green
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: messaging-app
    environment: blue
---
apiVersion: v1
kind: Service
metadata:
  name: messaging-app-blue-service
  labels:
    app: messaging-app
    environment: blue
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: messaging-app
    environment: blue
---
apiVersion: v1
kind: Service
metadata:
  name: messaging-app-green-service
  labels:
    app: messaging-app
    environment: green
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: messaging-app
    environment: green
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: messaging-app-blue-green-ingress
  labels:
    app: messaging-app
    strategy: blue-green
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/upstream-vhost: "messaging-app.local"
spec:
  ingressClassName: nginx
  rules:
  - host: messaging-app.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: messaging-app-blue-green-service
            port:
              number: 8000
  - host: blue.messaging-app.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: messaging-app-blue-service
            port:
              number: 8000
  - host: green.messaging-app.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: messaging-app-green-service
            port:
              number: 8000

